# Generated by Django 5.1.4 on 2025-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='database',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='graphics_design',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='troubleshooting',
        ),
        migrations.AddField(
            model_name='userskills',
            name='ai_ml',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='communication_skills',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='computer_architecture',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='computer_forensics_fundamentals',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='database_fundamentals',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='distributed_computing_systems',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='graphics_designing',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='networking',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='programming_skills',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='project_management',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='software_development',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='software_engineering',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='technical_communication',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AddField(
            model_name='userskills',
            name='troubleshooting_skills',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='max_salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='min_salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='business_analysis',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='cyber_security',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='data_science',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Poor'), (2, 'Beginner'), (3, 'Average'), (4, 'Intermediate'), (5, 'Professional'), (6, 'Excellent')], default=0),
        ),
    ]
