# Generated by Django 5.1.4 on 2025-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_career_remove_userskills_architecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
