# Generated by Django 5.1.4 on 2025-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_skill_userjobrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='interview_qna',
            field=models.JSONField(default=list),
        ),
    ]
